[package]
name = "calls"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ink_core = { git = "https://github.com/paritytech/ink/", package = "ink_core", default-features = false }
ink_model = { git = "https://github.com/paritytech/ink/", package = "ink_model", default-features = false }
ink_lang = { git = "https://github.com/paritytech/ink/", package = "ink_lang", default-features = false }
ink_types_node_runtime = { path = "../../", default-features = false }
parity-codec = { version = "4.1", default-features = false, features = ["derive"] }

[lib]
name = "calls"
crate-type = ["cdylib"]

[features]
default = [
    "std",
    "ink_lang/generate-api-description"
]
std = [
    "ink_core/std",
    "ink_model/std",
    "ink_lang/std",
    "ink_types_node_runtime/std",
    "parity-codec/std",
]
test-env = [
    "std",
    "ink_core/test-env",
    "ink_model/test-env",
    "ink_lang/test-env",
]
generate-api-description = [
    "ink_lang/generate-api-description"
]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
overflow-checks = true
